/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvantageItem: typeof import('./src/components/AdvantageItem.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader/AppHeader.vue')['default']
    BaseAdvantages: typeof import('./src/components/BaseAdvantages.vue')['default']
    BaseTitle: typeof import('./src/components/BaseTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateAccordion: typeof import('./src/components/TemplateAccordion/TemplateAccordion.vue')['default']
    TemplateAdvantages: typeof import('./src/components/TemplateAdvantages/TemplateAdvantages.vue')['default']
    TemplateFirstScreen: typeof import('./src/components/TemplateFirstScreen/TemplateFirstScreen.vue')['default']
    TemplateFirstScreenFirstScreenTitle: typeof import('./src/components/TemplateFirstScreen/FirstScreenTitle.vue')['default']
    TemplateServices: typeof import('./src/components/TemplateServices/TemplateServices.vue')['default']
    TemplateSliderReview: typeof import('./src/components/TemplateSliderReview/TemplateSliderReview.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UiAppLogo: typeof import('./src/components/ui/AppLogo.vue')['default']
    UiIconsIconCheck: typeof import('./src/components/ui/icons/IconCheck.vue')['default']
    UiIconsIconCommunity: typeof import('./src/components/ui/icons/IconCommunity.vue')['default']
    UiIconsIconDocumentation: typeof import('./src/components/ui/icons/IconDocumentation.vue')['default']
    UiIconsIconEcosystem: typeof import('./src/components/ui/icons/IconEcosystem.vue')['default']
    UiIconsIconSupport: typeof import('./src/components/ui/icons/IconSupport.vue')['default']
    UiIconsIconTooling: typeof import('./src/components/ui/icons/IconTooling.vue')['default']
    UiIconsLogo: typeof import('./src/components/ui/icons/Logo.vue')['default']
    UiLink: typeof import('./src/components/ui/Link.vue')['default']
    UiTemplateLink: typeof import('./src/components/ui/TemplateLink.vue')['default']
    UiTemplateNav: typeof import('./src/components/ui/TemplateNav.vue')['default']
    UiTemplateNavItem: typeof import('./src/components/ui/TemplateNavItem.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
